import { Injectable, Logger } from '@nestjs/common';
import { Context } from 'telegraf';
import { PkgCoreApiService } from '../../api/pkg-core-api.service';

/**
 * Callback data format for fact conflict resolution (standardized short prefixes):
 * - f_n:<shortId>  → Use new fact, deprecate old
 * - f_o:<shortId>  → Keep old fact, reject new
 * - f_b:<shortId>  → Keep both facts (COEXIST)
 *
 * These prefixes match FACT_CALLBACK_PREFIX from pkg-core.
 */
const FACT_CALLBACK_PREFIX = {
  NEW: 'f_n:',
  OLD: 'f_o:',
  BOTH: 'f_b:',
} as const;

const FACT_CALLBACK_PREFIXES = [
  FACT_CALLBACK_PREFIX.NEW,
  FACT_CALLBACK_PREFIX.OLD,
  FACT_CALLBACK_PREFIX.BOTH,
] as const;

type FactResolution = 'new' | 'old' | 'both';

interface ParsedFactCallback {
  resolution: FactResolution;
  shortId: string;
}

/**
 * Handler for fact conflict callback queries.
 *
 * These callbacks are generated by FactConflictService when a fact conflict
 * requires human resolution. The user sees three buttons:
 * - ✅ Новый → Use the new fact
 * - ❌ Старый → Keep the existing fact
 * - 🔀 Оба → Keep both facts
 */
@Injectable()
export class FactCallbackHandler {
  private readonly logger = new Logger(FactCallbackHandler.name);

  constructor(private readonly pkgCoreApi: PkgCoreApiService) {}

  /**
   * Check if this handler can process the callback
   */
  canHandle(callbackData: string): boolean {
    return FACT_CALLBACK_PREFIXES.some((prefix) => callbackData.startsWith(prefix));
  }

  /**
   * Handle callback query
   */
  async handle(ctx: Context): Promise<void> {
    const callbackQuery = ctx.callbackQuery;
    if (!callbackQuery || !('data' in callbackQuery)) {
      return;
    }

    const callbackData = callbackQuery.data;
    const parsed = this.parseCallback(callbackData);

    if (!parsed) {
      this.logger.warn(`Invalid fact callback data: ${callbackData}`);
      await ctx.answerCbQuery('Invalid callback');
      return;
    }

    const { resolution, shortId } = parsed;

    this.logger.log(`Processing fact conflict resolution: ${resolution} for ${shortId}`);

    try {
      const result = await this.pkgCoreApi.resolveFactConflict(shortId, resolution);

      if (!result.success) {
        await ctx.answerCbQuery(result.error || 'Ошибка');

        // Update message to show error
        await ctx.editMessageText(
          `❌ Ошибка: ${result.error || 'Не удалось обработать'}`,
          { parse_mode: 'HTML' },
        );
        return;
      }

      // Update message based on resolution
      const feedbackMessage = this.getResolutionFeedback(resolution, result.action);
      await ctx.editMessageText(feedbackMessage, { parse_mode: 'HTML' });

      // Answer callback query
      await ctx.answerCbQuery(this.getShortFeedback(resolution));
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      this.logger.error(`Failed to resolve fact conflict: ${errorMessage}`, error);

      // Check for "message not modified" error
      if (this.isMessageNotModifiedError(error)) {
        await ctx.answerCbQuery();
        return;
      }

      await ctx.answerCbQuery('Ошибка сервера');
    }
  }

  /**
   * Parse callback data into resolution and shortId
   */
  private parseCallback(callbackData: string): ParsedFactCallback | null {
    // Map prefix to resolution type
    const prefixToResolution: Record<string, FactResolution> = {
      [FACT_CALLBACK_PREFIX.NEW]: 'new',
      [FACT_CALLBACK_PREFIX.OLD]: 'old',
      [FACT_CALLBACK_PREFIX.BOTH]: 'both',
    };

    for (const prefix of FACT_CALLBACK_PREFIXES) {
      if (callbackData.startsWith(prefix)) {
        const shortId = callbackData.substring(prefix.length);

        if (!shortId) {
          return null;
        }

        return {
          resolution: prefixToResolution[prefix],
          shortId,
        };
      }
    }
    return null;
  }

  /**
   * Get feedback message for the user after resolution
   */
  private getResolutionFeedback(resolution: FactResolution, action?: string): string {
    switch (resolution) {
      case 'new':
        return `✅ <b>Принят новый факт</b>\n\nСтарый факт помечен как устаревший.`;
      case 'old':
        return `✅ <b>Сохранён старый факт</b>\n\nНовый факт отклонён.`;
      case 'both':
        return `✅ <b>Сохранены оба факта</b>\n\nОба факта сосуществуют в базе.`;
      default:
        return `✅ <b>Конфликт разрешён</b>`;
    }
  }

  /**
   * Get short feedback for answerCbQuery
   */
  private getShortFeedback(resolution: FactResolution): string {
    switch (resolution) {
      case 'new':
        return '✅ Новый факт принят';
      case 'old':
        return '✅ Старый факт сохранён';
      case 'both':
        return '✅ Оба факта сохранены';
      default:
        return '✅ Готово';
    }
  }

  /**
   * Check if error is "message not modified"
   */
  private isMessageNotModifiedError(error: unknown): boolean {
    if (error instanceof Error) {
      return error.message.includes('message is not modified');
    }
    return false;
  }
}
